export const STATE_ABBREVIATIONS = [
  'AL',
  'AK',
  'AZ',
  'AR',
  'CA',
  'CO',
  'CT',
  'DE',
  'DC',
  'FL',
  'GA',
  'HI',
  'ID',
  'IL',
  'IN',
  'IA',
  'KS',
  'KY',
  'LA',
  'ME',
  'MT',
  'NE',
  'NV',
  'NH',
  'NJ',
  'NM',
  'NY',
  'NC',
  'ND',
  'OH',
  'OK',
  'OR',
  'MD',
  'MA',
  'MI',
  'MN',
  'MS',
  'MO',
  'PA',
  'RI',
  'SC',
  'SD',
  'TN',
  'TX',
  'UT',
  'VT',
  'VA',
  'WA',
  'WV',
  'WI',
  'WY'
];

/* eslint-disable max-len*/
export const APP_DESCRIPTION = 'This tools computes principal component analysis (PCA) of two or more variables (selected below right) for each of the 50 US states plus District of Columbia (DC).  If a single variable is selected, the states are colored by that variable.  With two or more variables selected, the coordinates of the states along the first two principal components are shown in the scatterplot (below left), in which the first principal component is horizontal, and the second is vertical. The states are colored by the 2D colormap behind the scatterplot. The coordinate axes of each variable are projected into the same space (shown as colored lines), to indicate how the individual variables align with the principal components. States can be selected or unselected by clicking on them either in the map or scatterplot view.';
/* eslint-enable max-len */

export const PCA_COLUMNS_COLORS = {
  Obesity: '#19CDD7',
  InfantMortality: '#DDB27C',
  Unemployment: '#88572C',
  SNAP: '#FF991F',
  Poverty: '#F15C17',
  HigherEducation: '#223F9A',
  MoreDemocrat16: '#DA70BF',
  MoreDemocrat12: '#125C77',
  MoreDemocrat08: '#4DC19C',
  MoreDemocrat: '#776E57'
};
